### ISSUE TITLE
Take out the "Camera" option for photo upload

### ISSUE THREAD

**Issue by Kevinxu99** [new-dawn/new_dawn_ios_playground#174]
Camera function not implemented yet and will force the app to quit.
Take out the option from the photo upload page for now until further changes are made.

**Comment by tangziyi001** [comment]
Code pointer: https://github.com/new-dawn/new_dawn_ios_playground/blob/04570efd26dbf735e023b6ee5f8c9e061aedeb0b/NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_PhotosUpload.swift#L157-L172

**Comment by tangziyi001** [comment]
Should be easy. @Kevinxu99 Will assign you a new task once you finish this.
